import Head from "next/head";
import Favicon from "home/components/GlobalComponents/Favicon";
import styles from "home/styles/Login.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by c%reate next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Favicon />
      </Head>
      <body className={styles.loginBody}>
        <div className={styles.loginContainer}>
          <div className={styles.logoWrapper}>
            <img
              src="/images/LogoFull.svg"
              alt="Samosas IT"
              className={styles.logo}
            />
          </div>
          <h2>Welcome Back!</h2>
          <p className={styles.loginSubheading}>Please enter your details</p>
          <form className={styles.loginForm}>
            <div className={styles.inputGroup}>
              <label className={styles.inputLabel} htmlFor="email">
                Email id
              </label>
              <input
                className={styles.inputBox}
                type="email"
                id="email"
                placeholder="yourmail@abc.com"
                required
              />
            </div>
            <div className={styles.inputGroup}>
              <label className={styles.inputLabel} htmlFor="password">
                Password
              </label>
              <input
                className={styles.inputBox}
                type="password"
                id="password"
                placeholder="************"
                required
              />
            </div>
            <div className="forgot-password">
              <a href="/forgot-password" className={styles.forgotPassword}>
                Forgot Password?
              </a>
            </div>
            <button className={styles.loginButton} type="submit">
              Log in
            </button>
          </form>
          <div className={styles.signupWrapper}>
            <p>
              Don't you have an account?{" "}
              <a className={styles.signupLink} href="/signup">
                Sign up
              </a>
            </p>
          </div>
        </div>
      </body>
    </>
  );
}
